name: Push Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    name: Test

    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [12, 14, 16]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout the release target branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
